#!/bin/bash

# Configuration
PREFIX=devstack
COMPOSE=PATH/TO/docker-compose.yml
USER=dfx

# Functions
usage() {
cat << EOF
Usage: ${0##*/} [-h]

Control your devstack.

Options:

  -h          Display this help and exit.

Commands:
  up          Start the devstack.
  stop        Stop the devstack.
  die         Destroy the devstack.
  logs        Follow the devstack logs.
  exec        Exec command in container.
  g|go        Attach container in devstack.
  gu|gou      Attach container in devstack as user.
EOF
}

call() {
	docker-compose -p $PREFIX -f $COMPOSE $*
}

run() {
	call up -d
}

stop() {
	call stop
}

destroy() {
	call stop
	call rm --all
}

logs() {
	call logs -f
}

fire() {
	call exec $1
}

go() {
	call exec $1 /bin/bash
}

gou() {
	call exec $1 su $USER
}

# Main switch
case "$1" in
	up)
		run
		exit 0
		;;
	stop)
		stop
		exit 0
		;;
	die)
		destroy
		exit 0
		;;
	logs)
		logs
		exit 0
		;;
	exec)
		fire
		exit 0
		;;
	g)
		go $2 $3
		exit 0
		;;
	go)
		go $2 $3
		exit 0
		;;
	gu)
		gou $2
		exit 0
		;;
	gou)
		gou $2
		exit 0
		;;
	*)
		usage
		exit 1
		;;
esac
shift
