version: '2'

services:
  apache:
    image: dockette/devstack:apache

    networks:
      default:
        ipv4_address: 172.10.10.5

    volumes_from:
      - data

    ports:
      - 80:80
      - 443:443

    links:
      - php72:php
      - php72:php7
      # - php56:php56

  php72:
    image: dockette/devstack:php72-fpm

    networks:
      default:
        ipv4_address: 172.10.10.10

    environment:
      - SSH_AUTH_SOCK=/ssh-agent

    volumes_from:
      - data
      - userdirs

    links:
      - mariadb:mysql
      # - postgresql:postgresql
      # - blackfire:blackfire

  # php56:
  #   image: dockette/devstack:php56-fpm

  #   networks:
  #     default:
  #       ipv4_address: 172.10.10.11

  #   environment:
  #     - SSH_AUTH_SOCK=/ssh-agent

  #   volumes_from:
  #     - data
  #     - userdirs

  #   links:
  #     - mariadb:mysql
  #     - postgresql:postgresql
  #     - blackfire:blackfire

  # nodejs:
  #   image: dockette/devstack:nodejs

  #   networks:
  #     default:
  #       ipv4_address: 172.10.10.12

  #   # Keep this service alive
  #   tty: true
  #   stdin_open: true

  #   environment:
  #     - SSH_AUTH_SOCK=/ssh-agent

  #   volumes_from:
  #     - data
  #     - userdirs

  #   links:
  #     - mariadb:mysql
  #     - postgresql:postgresql

  # blackfire:
  #   image: blackfire/blackfire

  #   environment:
  #     - BLACKFIRE_SERVER_ID=<fill-me>
  #     - BLACKFIRE_SERVER_TOKEN=<fill-me>

  adminer:
    image: dockette/adminer:dg

    networks:
      default:
        ipv4_address: 172.10.10.13

    ports:
      - 8000:80

    links:
      - mariadb:mysql
      # - postgresql:postgresql

  mariadb:
    image: mariadb:10.1

    networks:
      default:
        ipv4_address: 172.10.10.20

    ports: 
      - 3306:3306

    volumes:
      - ./data/mariadb:/var/lib/mysql

    environment:
      # Change in your devstack!
      - MYSQL_ROOT_PASSWORD=root

  # postgresql:
  #   image: postgres:9.6

  #   networks:
  #     default:
  #       ipv4_address: 172.10.10.21

  #   ports: 
  #     - 5432:5432

  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  #   environment:
  #     # Change in your devstack!
  #     - POSTGRES_PASSWORD=root

  data:
    image: busybox

    volumes:
      # Data homeland
       - ~/projects:/srv

  userdirs:
    image: busybox

    volumes:
      # It's root's home folder. 
      # You can store here .npm, .composer cache etc.
      - ./data/root-dir:/root
      # It's dfx's home folder. 
      # You can store here .npm, .composer cache etc.
      - ./data/dfx-dir:/home/dfx
      # Propagate SSH agent to containers
      - $SSH_AUTH_SOCK:/ssh-agent

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      # This is useful for PHP xdebug debugging
      - subnet: 172.10.10.0/24
        gateway: 172.10.10.1
