; Update memory
memory_limit = 512M
upload_max_filesize = 2048M
post_max_size = 2048M

; No disabled functions
disable_functions =

; Mailer
sendmail_path = /usr/local/bin/phpmailer

; Xdebug
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.idekey = PHPSTORM
xdebug.client_host = 172.10.10.1
xdebug.client_port = 9003
